all: campuseinstein kleineulme mensastgeorg suedmensa ulme69

campuseinstein:
	./favicon.bash ../../logo/avatar_$@.png $@

kleineulme:
	./favicon.bash ../../logo/avatar_$@.png $@

mensastgeorg:
	./favicon.bash ../../logo/avatar_$@.png $@

suedmensa:
	./favicon.bash ../../logo/avatar_$@.png $@

ulme69:
	./favicon.bash ../../logo/avatar_$@.png $@

clean:
	rm -fr campuseinstein kleineulme mensastgeorg suedmensa ulme69
