all: campuseinstein kleineulme mensastgeorg suedmensa ulme69

campuseinstein:
	./favicon.bash ../../logo/avatar_$@.png $@
	cp ../../logo/avatar_$@.png $@/avatar.png

kleineulme:
	./favicon.bash ../../logo/avatar_$@.png $@
	cp ../../logo/avatar_$@.png $@/avatar.png

mensastgeorg:
	./favicon.bash ../../logo/avatar_$@.png $@
	cp ../../logo/avatar_$@.png $@/avatar.png

suedmensa:
	./favicon.bash ../../logo/avatar_$@.png $@
	cp ../../logo/avatar_$@.png $@/avatar.png

ulme69:
	./favicon.bash ../../logo/avatar_$@.png $@
	cp ../../logo/avatar_$@.png $@/avatar.png

clean:
	rm -fr campuseinstein kleineulme mensastgeorg suedmensa ulme69
